%RUN_SMOKE_PIPELINE Quick end-to-end pipeline smoke test (~5-10 minutes).
%
% From repo root:
%   matlab -batch "run('scripts/run_smoke_pipeline.m')"

setup_repo_paths();
tStart = tic;

resultDir = fullfile('results', 'smoke');
figureDir = fullfile('figures', 'smoke');
screenFile = fullfile(resultDir, 'results_deterministic_screen_smoke.csv');
selectedFile = fullfile(resultDir, 'selected_parameter_sets_smoke.csv');
ssaFile = fullfile(resultDir, 'results_ssa_kl_smoke.csv');
exampleFile = fullfile(resultDir, 'ssa_example_E0_E1_distributions.csv');
summaryFile = fullfile(resultDir, 'summary.md');

fprintf('\n=== Smoke pipeline ===\n');

run_deterministic_screen( ...
    'N_runs', 50, ...
    'n_E_vals', 50, ...
    'useParallel', false, ...
    'outputFile', screenFile, ...
    'randomSeed', 1);

select_parameter_sets( ...
    'inputFile', screenFile, ...
    'N_select', 12, ...
    'oversampleFactor', 1.0, ...
    'outputFile', selectedFile, ...
    'randomSeed', 2, ...
    'stratifyBy', 'average_phi');

run_ssa_kl_on_selected( ...
    'inputFile', selectedFile, ...
    'N_stoch', 50, ...
    't_end_stoch', 25, ...
    'nBins', 10, ...
    'useParallel', false, ...
    'batchSize', 4, ...
    'outputFile', ssaFile, ...
    'randomSeed', 3, ...
    'exampleDistributionFile', exampleFile);

plot_pipeline_results( ...
    'screenFile', screenFile, ...
    'ssaFile', ssaFile, ...
    'exampleDistributionFile', exampleFile, ...
    'outputDir', figureDir);

write_pipeline_summary(screenFile, selectedFile, ssaFile, summaryFile, struct( ...
    'name', "smoke", ...
    'notes', ["Settings: N_runs=50, n_E_vals=50, N_select=12, N_stoch=50, t_end_stoch=25, nBins=10."; ...
              "Smoke run validates the pipeline path; KL values are for integration testing only."]));

fprintf('\nSmoke pipeline finished in %.1f minutes.\n', toc(tStart)/60);
fprintf('Outputs: %s, %s\n', resultDir, figureDir);
