%RUN_FULL_PIPELINE_TEMPLATE Template for large production runs.
%
% WARNING: Full-scale SSA can take many hours or days. Review SSA feasibility
% on the first-result pipeline before uncommenting and running this script.
%
% From repo root (after editing settings):
%   matlab -batch "run('scripts/run_full_pipeline_template.m')"

setup_repo_paths();

warning(['Full pipeline template is disabled. ', ...
    'Edit and uncomment the block below after reviewing first-result SSA feasibility.']);
return;

%% --- Uncomment below after SSA feasibility review ---

% resultDir = fullfile('results', 'full');
% figureDir = fullfile('figures', 'full');
% screenFile = fullfile(resultDir, 'results_deterministic_screen.csv');
% selectedFile = fullfile(resultDir, 'selected_parameter_sets.csv');
% ssaFile = fullfile(resultDir, 'results_ssa_kl.csv');
% exampleFile = fullfile(resultDir, 'ssa_example_E0_E1_distributions.csv');
% summaryFile = fullfile(resultDir, 'summary.md');
%
% % Large deterministic screen (hours). Consider n_E_vals=150 instead of 500.
% run_deterministic_screen( ...
%     'N_runs', 10000, ...
%     'n_E_vals', 150, ...
%     'useParallel', true, ...
%     'outputFile', screenFile, ...
%     'randomSeed', 1);
%
% select_parameter_sets( ...
%     'inputFile', screenFile, ...
%     'N_select', 100, ...
%     'oversampleFactor', 1.5, ...
%     'outputFile', selectedFile, ...
%     'randomSeed', 2, ...
%     'stratifyBy', 'average_phi');
%
% % SSA stage: increase N_stoch and t_end_stoch only after convergence checks.
% % Legacy brute-force used t_end_stoch=1500, N_stoch=200, nBins=40 — do not
% % use those defaults without validation.
% run_ssa_kl_on_selected( ...
%     'inputFile', selectedFile, ...
%     'N_stoch', 100, ...
%     't_end_stoch', 50, ...
%     'nBins', 10, ...
%     'useParallel', true, ...
%     'batchSize', 25, ...
%     'outputFile', ssaFile, ...
%     'randomSeed', 3, ...
%     'exampleDistributionFile', exampleFile);
%
% plot_pipeline_results( ...
%     'screenFile', screenFile, ...
%     'ssaFile', ssaFile, ...
%     'exampleDistributionFile', exampleFile, ...
%     'outputDir', figureDir);
%
% write_pipeline_summary(screenFile, selectedFile, ssaFile, summaryFile, struct( ...
%     'name', 'full_template', ...
%     'notes', {'Edit settings before running. Expect long runtime.'}));
