%RUN_DIMENSIONLESS_SMOKE_PIPELINE Quick smoke test of the paper-inspired
% dimensionless analysis mode (a few minutes, bounded).
%
% From repo root:
%   matlab -batch "run('scripts/run_dimensionless_smoke_pipeline.m')"
%
% This keeps Ishfaq's enzyme ODE/SSA model but runs it dimensionlessly:
%   ATP=1, RT=1 (phi and delta_mu in kBT-like units), symmetric rate ranges
%   10^-2..10^2, E0=0.95*E*, E1=1.05*E*. The headline figure is JS divergence
%   (bounded), not the epsilon-saturated raw KL plot.

setup_repo_paths();
tStart = tic;

mode = 'paper_inspired_dimensionless';
resultDir = fullfile('results', 'dimensionless_smoke');
figureDir = fullfile('figures', 'dimensionless_smoke');
screenFile = fullfile(resultDir, 'results_deterministic_screen_smoke.csv');
selectedFile = fullfile(resultDir, 'selected_parameter_sets_smoke.csv');
ssaFile = fullfile(resultDir, 'results_ssa_kl_smoke.csv');
exampleFile = fullfile(resultDir, 'ssa_example_E0_E1_distributions.csv');
summaryFile = fullfile(resultDir, 'summary.md');

fprintf('\n=== Dimensionless smoke pipeline (paper-inspired) ===\n');

run_deterministic_screen( ...
    'mode', mode, ...
    'N_runs', 60, ...
    'n_E_vals', 60, ...
    'useParallel', false, ...
    'outputFile', screenFile, ...
    'randomSeed', 1);

select_parameter_sets( ...
    'inputFile', screenFile, ...
    'N_select', 12, ...
    'oversampleFactor', 1.0, ...
    'outputFile', selectedFile, ...
    'randomSeed', 2, ...
    'stratifyBy', 'average_phi');

run_ssa_kl_on_selected( ...
    'mode', mode, ...
    'inputFile', selectedFile, ...
    'N_stoch', 50, ...
    't_end_stoch', 25, ...
    'nBins', 10, ...
    'useParallel', false, ...
    'batchSize', 4, ...
    'outputFile', ssaFile, ...
    'randomSeed', 3, ...
    'exampleDistributionFile', exampleFile);

plot_pipeline_results( ...
    'mode', mode, ...
    'screenFile', screenFile, ...
    'ssaFile', ssaFile, ...
    'exampleDistributionFile', exampleFile, ...
    'outputDir', figureDir);

plot_response_curves( ...
    'mode', mode, ...
    'selectedFile', selectedFile, ...
    'screenFile', screenFile, ...
    'outputFile', fullfile(figureDir, 'fig_example_response_curves.png'));

write_pipeline_summary(screenFile, selectedFile, ssaFile, summaryFile, struct( ...
    'name', "dimensionless_smoke", ...
    'notes', ["Mode: paper_inspired_dimensionless (enzyme-model analogy, NOT the PNAS Markov model)."; ...
              "Units: ATP=1, RT=1; phi and delta_mu are in kBT-like units."; ...
              "Rate ranges symmetric 10^-2..10^2; E0=0.95*E*, E1=1.05*E*."; ...
              "Settings: N_runs=60, n_E_vals=60, N_select=12, N_stoch=50, t_end_stoch=25, nBins=10."; ...
              "Headline metric: JS divergence (bounded). Raw KL kept for continuity but can saturate near -ln(epsilon)~34."; ...
              "Smoke run validates the dimensionless path; values are for integration testing only."]));

fprintf('\nDimensionless smoke pipeline finished in %.1f minutes.\n', toc(tStart)/60);
fprintf('Outputs: %s, %s\n', resultDir, figureDir);
